<?php
return [
    'env' => env('APP_ENV', 'production'),
    'debug' => env('APP_DEBUG', false),
    'url' => env('APP_URL', 'http://mrcoc.work/lar52-framework/public/'),
    'backendUrl' => env('APP_BACKEND_URL', 'admin'),
    'timezone' => 'UTC',
    'locale' => 'vn',
    'fallback_locale' => 'vn',
    'key' => env('APP_KEY'),
    'cipher' => 'AES-256-CBC',
    'log' => env('APP_LOG', 'single'),
    'log_level' => env('APP_LOG_LEVEL', 'debug'),
    'api_crm' => env('API_CRM',''),
    'api_key' => env('API_KEY',''),
    'vnpay' => array(
        'enable' => TRUE,
        'isSandbox' => TRUE,
        'vnp_hashsecret' => 'DYFUUENPDWPQMOSYWYDPHOPNNALQTPLB',
        'vnp_merchant' => 'VNPAY',
        'vnp_tmncode' => 'CLOUDPRO',
        'currency_code' => 'VND',
        'locale' => 'vn',
    ),
    'providers' => array(
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,
        igaster\laravelTheme\themeServiceProvider::class,
        Collective\Html\HtmlServiceProvider::class,
        Jenssegers\Mongodb\MongodbServiceProvider::class,
        Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class,

        App\Providers\AppServiceProvider::class,
        App\Providers\HelperServiceProvider::class,
        Backend\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        Api\Providers\ApiServiceProvider::class,
        Frontend\Providers\FrontendServiceProvider::class,
        Backend\Providers\BackendServiceProvider::class,
    ),

    'aliases' => [
        'App' => Illuminate\Support\Facades\App::class,
        'Artisan' => Illuminate\Support\Facades\Artisan::class,
        'Auth' => Illuminate\Support\Facades\Auth::class,
        'Blade' => Illuminate\Support\Facades\Blade::class,
        'Cache' => Illuminate\Support\Facades\Cache::class,
        'Config' => Illuminate\Support\Facades\Config::class,
        'Cookie' => Illuminate\Support\Facades\Cookie::class,
        'Crypt' => Illuminate\Support\Facades\Crypt::class,
        'DB' => Illuminate\Support\Facades\DB::class,
        'Event' => Illuminate\Support\Facades\Event::class,
        'File' => Illuminate\Support\Facades\File::class,
        'Gate' => Illuminate\Support\Facades\Gate::class,
        'Hash' => Illuminate\Support\Facades\Hash::class,
        'Lang' => Illuminate\Support\Facades\Lang::class,
        'Log' => Illuminate\Support\Facades\Log::class,
        'Mail' => Illuminate\Support\Facades\Mail::class,
        'Password' => Illuminate\Support\Facades\Password::class,
        'Queue' => Illuminate\Support\Facades\Queue::class,
        'Redirect' => Illuminate\Support\Facades\Redirect::class,
        'Redis' => Illuminate\Support\Facades\Redis::class,
        'Request' => Illuminate\Support\Facades\Request::class,
        'Response' => Illuminate\Support\Facades\Response::class,
        'Route' => Illuminate\Support\Facades\Route::class,
        'Schema' => Illuminate\Support\Facades\Schema::class,
        'Session' => Illuminate\Support\Facades\Session::class,
        'Storage' => Illuminate\Support\Facades\Storage::class,
        'URL' => Illuminate\Support\Facades\URL::class,
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View' => Illuminate\Support\Facades\View::class,
        'Theme' => igaster\laravelTheme\Facades\Theme::class,
        'Form' => Collective\Html\FormFacade::class,
        'Html' => Collective\Html\HtmlFacade::class,
        'Eloquent' => Jenssegers\Mongodb\Eloquent\Model::class,
        'JWTAuth' => Tymon\JWTAuth\Facades\JWTAuth::class,
        'JWTFactory' => 'Tymon\JWTAuth\Facades\JWTFactory',

        /*Helper*/
        'HelperCommon' => App\Helpers\Common::class,
        'HelperUser' => App\Helpers\User::class,
        'HelperImages' => App\Helpers\Images::class,
        'HelperCurrency' => App\Helpers\Currency::class,
        'HelperNumber' => App\Helpers\Number::class,
    ],

];
